apiVersion: v1
kind: Service
metadata:
  name: simple-static-webpage-service
spec:
  selector:
    app: simple-static-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
